[tool.poetry]
name = "fastapi-sso"
version = "0.4.0"
description = "FastAPI plugin to enable SSO to most common providers (such as Facebook login, Google login and login via Microsoft Office 365 Account)"
authors = ["Tomas Votava <info@tomasvotava.eu>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/tomasvotava/fastapi-sso"
homepage = "https://tomasvotava.github.io/fastapi-sso/"
documentation = "https://tomasvotava.github.io/fastapi-sso/"
keywords = ["fastapi", "sso", "oauth", "google", "facebook", "spotify"]

[tool.black]
line_length = 119

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
fastapi = "<1"
oauthlib = ">=3.1.0"
starlette = ">=0.13.6"
pydantic = ">=1.8.1"
httpx = "^0.20.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pylint = "^2.7.2"
fastapi = "<1"
pdoc3 = "^0.9.2"
uvicorn = "^0.17.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
